name: Daily Commit

on:
  schedule:
    # Runs every day at 6:00 AM UTC (adjust as needed)
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allows manual trigger

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make a dummy file change (23f3004030@ds.study.iitm.ac.in)
        run: |
          echo "Daily run on $(date)" >> daily-log.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add daily-log.txt
          git commit -m "Automated daily commit on $(date)"
          git push
